---

- job:
    name: rancher-integration
    parent: tox
    description: |
      Prepare Rancher/Selenium
    pre-run: playbooks/rancher-kontainer/pre.yaml
    abstract: true
    nodeset: ubuntu-focal
    vars:
      rancher_image: rancher/rancher:v2.4.8
      tox_envlist: register
      python_version: 3.8
      bindep_profile: test py38

- job:
    name: rancher-integration-devel
    parent: rancher-integration
    description: |
      Prepare Rancher/Selenium and build driver from sources
    pre-run:
      - playbooks/rancher-kontainer/prepare_artifacts.yaml
    abstract: true
    vars:
      # Building ui driver
      node_version: 14
      kontainer_project_src_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/opentelekomcloud/kontainer-engine-driver-otc'].src_dir }}"
      ui_project_src_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/opentelekomcloud/ui-cluster-driver-otc'].src_dir }}"
        #    nodeset:
        #      nodes:
        #        - name: rancher
        #          # node 10 exists from focal
        #          label: ubuntu-focal
    required-projects:
      - opentelekomcloud/kontainer-engine-driver-otc
      - opentelekomcloud/ui-cluster-driver-otc

- job:
    name: rancher-register-driver-latest
    parent: rancher-integration
    description: |
      Test the latest released artifacts
    vars:
      tox_envlist: register

- job:
    name: rancher-register-driver-devel
    parent: rancher-integration-devel
    description: |
      Test the devel artifacts
    vars:
      tox_envlist: register
        #      tox_environment:
        # vars come from playbooks/rancher-kontainer/prepare_artifacts.yaml
        # DRIVER_LOCATION: "{{ rancher_driver_location }}"
        # DRIVER_UI_LOCATION: "{{ rancher_ui_location }}"

- job:
    name: rancher-kontainer-integration
    parent: tox-py38
    description: |
      Run Functional tests of the driver on Rancher+OTC.
    pre-run: playbooks/rancher-kontainer/pre.yaml
      #run: playbooks/rancher-kontainer/run.yaml
    vars:
      functest_project_name: "eu-de_zuul_rancher"
      rancher_image: rancher/rancher:v2.4.8
      python_version: 3.8
      node_version: 10
      kontainer_project_src_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/opentelekomcloud/kontainer-engine-driver-otc'].src_dir }}"
      ui_project_src_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/opentelekomcloud/ui-cluster-driver-otc'].src_dir }}"
    nodeset:
      nodes:
        - name: rancher
          label: ubuntu-focal
            #    required-projects:
            #      - opentelekomcloud/kontainer-engine-driver-otc
            #      - opentelekomcloud/ui-cluster-driver-otc


- project:
    check:
      jobs:
        - tox-pep8
        - rancher-register-driver-latest
        - rancher-register-driver-devel

