---

- job:
    name: rancher-register-driver
    parent: tox
    description: |
      Run Rancher/Selenium and register kontainer driver
    pre-run: playbooks/rancher-kontainer/pre.yaml
    vars:
      tox_envlist: register
      python_version: 3.8

- job:
    name: rancher-register-driver-latest
    parent: rancher-register-driver
    description: |
      Test the latest released artifacts

- job:
    name: rancher-kontainer-integration
    parent: tox-py38
    description: |
      Run Functional tests of the driver on Rancher+OTC.
    pre-run: playbooks/rancher-kontainer/pre.yaml
      #run: playbooks/rancher-kontainer/run.yaml
    vars:
      functest_project_name: "eu-de_zuul_rancher"
      rancher_image: rancher/rancher:v2.4.8
      python_version: 3.8
      node_version: 10
      kontainer_project_src_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/opentelekomcloud/kontainer-engine-driver-otc'].src_dir }}"
      ui_project_src_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/opentelekomcloud/ui-cluster-driver-otc'].src_dir }}"
    nodeset:
      nodes:
        - name: rancher
          label: ubuntu-focal
            #    required-projects:
            #      - opentelekomcloud/kontainer-engine-driver-otc
            #      - opentelekomcloud/ui-cluster-driver-otc


- project:
    check:
      jobs:
        - tox-pep8
        - rancher-register-driver-latest

