- name: Build kontainer driver
  include_role:
    name: goreleaser
  vars:
    goreleaser_args: "{{ kontainer_build_args }}"
    goreleaser_project_src_dir: "{{ kontainer_project_src_dir }}"

- name: Find tarballs in artifacts directory
  find:
    file_type: file
    paths: "{{ kontainer_project_src_dir }}/dist"
    patterns: "*.tar.gz"
  register: result

- name: Set fact for the Kontainer engine binary
  set_fact:
    rancher_kontainer_engine_tarball: "{{ result.files.0.path }}"
    rancher_kontainer_engine_tarball_base: "{{ result.files.0.path | basename }}"
    cacheable: true

- name: Create artifacts folder
  file:
    path: "{{ prepare_artifacts_dir }}"
    state: "directory"

- name: Place kontainer engine content into artifacts
  copy:
    # trailing slash important
    src: "{{ rancher_kontainer_engine_tarball }}"
    dest: "{{ prepare_artifacts_dir }}"
    remote_src: true
  register: res

- name: Find artifacts
  find:
    file_type: file
    paths: "{{ prepare_artifacts_dir }}"
    recurse: yes
  register: result

- name: debug artifacts
  debug:
    var: result

- name: start serving
  include_role:
    name: serve-artifacts
  vars:
    serve_artifacts_base_path: "{{ prepare_artifacts_dir }}"

- name: try fetch kontainer-driver
  uri:
    url: "http://{{ ansible_host }}:8080/{{ rancher_kontainer_engine_tarball_base }}"
  register: res
