---
# - hosts: all
#   tasks:
#     - name: Install binary dependencies
#       include_role:
#         name: bindep
#       vars:
#         bindep_dir: "{{ zuul_work_dir }}"
#       when: tox_install_bindep | default(true)

- hosts: all
  roles:
    - ensure-python
    - ensure-docker
    - ensure-go
    - ensure-goreleaser
    - ensure-javascript-build-tool

- hosts: all
  tasks:
    - name: set fact
      set_fact:
        cacheable: true
        tox_environment:
          RANCHER_BIND_HOST: "{{ ansible_default_ipv4.address }}"

    - name: Deploy rancher/selenium
      include_role:
        name: prepare-rancher-env
      vars:
        rancher_password: dummy_pass
