---
- hosts: all
  roles:
    - ensure-python
    - ensure-docker

- hosts: all
  tasks:
    - name: set fact
      set_fact:
        cacheable: true
        tox_environment:
          RANCHER_BIND_HOST: "{{ ansible_default_ipv4.address }}"

    - name: Deploy rancher/selenium
      include_role:
        name: prepare-rancher-env
      vars:
        rancher_password: dummy_pass
